<?php
$menu = array(
'show_menu '=>'显示组菜单<br><font color=#FF9797>格式:show_menu 组</font>',
'querytrade'=>'查询积分余额<br><font color=#FF9797>格式:querytrade</font>',
'top todayKills'=>'今日击杀排行榜<br><font color=#FF9797>格式:top todayKills</font>',
'top totalKills'=>'总击杀排行榜<br><font color=#FF9797>格式:top totalKills</font>',
'top todayHonorPoints'=>'今日荣誉排行榜<br><font color=#FF9797>格式:top todayHonorPoints</font>',
'top totalHonorPoints'=>'总荣誉排行榜<br><font color=#FF9797>格式:top totalHonorPoints</font>',
'top money'=>'金币排行榜<br><font color=#FF9797>格式:top money</font>',
'go '=>'传送到坐标<br><font color=#FF9797>格式:go 地图ID x坐标 y坐标 z坐标 o坐标</font>',
'recievetrade'=>'领取积分<br><font color=#FF9797>格式:recievetrade</font>',
'chongzhi'=>'使用充值卡充值<br><font color=#FF9797>格式:chongzhi</font>',
'gold'=>'金币积分互兑换<br><font color=#FF9797>格式:gold</font>',
'xp '=>'奖励经验<br><font color=#FF9797>格式:xp 奖励经验数值 最高等级</font>',
'level '=>'提升等级<br><font color=#FF9797>格式:level 每次提升级别 最高级别</font>',
'talent '=>'奖励天赋点<br><font color=#FF9797>格式:talent 奖励天赋点数</font>',
'buyvipplayer '=>'购买会员权限<br>会员等级相关信息请参照_vipinfo表<br><font color=#FF9797>格式:buyvipplayer VipLevel</font>',
'skilllevel'=>'提升技能熟练度<br><font color=#FF9797>格式:skilllevel</font>',
'show_bank'=>'打开银行<br><font color=#FF9797>格式:show_bank</font>',
'reset_talent'=>'重置天赋<br><font color=#FF9797>格式:reset_talent</font>',
'bind_pos'=>'炉石绑定<br><font color=#FF9797>格式:bind_pos</font>',
'activate_taxi'=>'激活飞行点<br><font color=#FF9797>格式:activate_taxi</font>',
'fix'=>'修理装备<br><font color=#FF9797>格式:fix</font>',
'AutoPay'=>'领取泡点工资<br><font color=#FF9797>格式:AutoPay</font>',
'rename'=>'角色重新命名<br><font color=#FF9797>格式:rename</font>',
'instanceUnbind'=>'重置副本<br><font color=#FF9797>格式:instanceUnbind</font>',
'ranks'=>'进入军衔提升系统<br><font color=#FF9797>格式:ranks</font>',
'lushi'=>'使用炉石,传送到炉石绑定地点<br><font color=#FF9797>格式:lushi</font>',
'ysxlsee'=>'查看元神修炼状态<br><font color=#FF9797>格式:ysxlsee</font>',
'ysxl liliang'=>'力量元神修炼<br><font color=#FF9797>格式:ysxl liliang</font>',
'ysxl mingjie'=>'敏捷元神修炼<br><font color=#FF9797>格式:ysxl mingjie</font>',
'ysxl naili'=>'耐力元神修炼<br><font color=#FF9797>格式:ysxl naili</font>',
'ysxl zhili'=>'智力元神修炼<br><font color=#FF9797>格式:ysxl zhili</font>',
'ysxl jingshen'=>'精神元神修炼<br><font color=#FF9797>格式:ysxl jingshen</font>',
'ranks up'=>'军衔提升关键指针(id=561不可更改)<br><font color=#FF9797>格式:ranks up</font>',
'show_auction'=>'打开拍卖行<br><font color=#FF9797>格式:show_auction</font>',
'castspell'=>'施放技能,可用于变形,召宠物,内域飞行等<br><font color=#FF9797>格式:castspell spellID</font>',
'pvp_switch'=>'积分PVP开关<br><font color=#FF9797>格式:pvp_switch</font>',
'returnm'=>'恢复变身,解除变身状态<br><font color=#FF9797>格式:returnm</font>',
'change'=>'变身,利用怪物模型+模型大小实现玩家变身功能<br><font color=#FF9797>格式:change 模型ID 模型大小</font>',
'DJ '=>'点歌服务<br><font color=#FF9797>格式:DJ 歌曲ID</font>',
'unknow'=>'变性别<br><font color=#FF9797>格式:unknow</font>',
'change_sex'=>'变性别<br><font color=#FF9797>格式:change_sex</font>',
'back'=>'解卡,回出生地 <br><font color=#FF9797>格式:back</font>',
'cjjk'=>'超级解卡,解卡战斗 <br><font color=#FF9797>格式:cjjk</font>',
'cmd '=>'超级命令,可以使用所有现有的GM命令<br>GM命令可以在command表中查找 <br><font color=#FF9797>格式:cmd [自己使用:0 可对目标使用:1] GM命令</font>',
'item_up'=>'升级宝石 itemID必须为9 <br>功能: 点击宝石再点击需要合成的物品 <br>合成公式在数据库_dq_item_up_list表中配置 <br><font color=#FF9797>格式:item_up</font>',
'xingyun'=>'幸运宝石 itemID必须为10 <br>功能: 提高合成成功率 <br><font color=#FF9797>格式:xingyun</font>',
'jinggu'=>'禁锢宝石 itemID必须为6 <br>功能: 合成失败也不会摧毁原始装备 <br><font color=#FF9797>格式:jinggu</font>',
);
	?>